# Path ways count
PATH_COUNT = 10
UPPER_PATH_WAY_BOUND_ID = 0
BOTTOM_PATH_WAY_BOUND_ID = PATH_COUNT - 1
# Server

MYSQL_HOST = 'localhost'
MYSQL_USER_NAME = 'root'
MYSQL_DB_NAME = 'game_cms'
MYSQL_PASSWORD = ''
SERVER_HOST = '0.0.0.0'
SERVER_PORT = 3005
SERVER_VERSION = 1101


MYSQL_CONNECTIONS_POOL = 5
REDIS_CONNECTIONS_POOL = 5
