module BattleStatuses
  PENDING = 1
  READY_TO_START = 2
  IN_PROGRESS = 3
  FINISHED = 4
end

module UnitStatuses
  MOVE = 1
  DIE = 3
  ATTACK = 4
  DEFAULT = 42
end

module Timings
  ITERATION_TIME = 0.1
  DEFAULT_UNITS_SPAWN_TIME = 5.0
  PING_TIME = 0.5
  DEFERRED_TASKS_PROCESS_TIME = 0.1
end

module PlayerStates
  LOGIN = 1
  IN_WORLD = 2
  IN_BATTLE = 3
  READY_TO_FIGHT = 4
end

module NetWorkingActions
  REQUEST_PLAYER = 1
  REQUEST_NEW_BATTLE = 2
  REQUEST_BATTLE_START = 3
  REQUEST_BATTLE_MAP_DATA = 4
  REQUEST_SPAWN_UNIT = 5
  REQUEST_PRODUCTION_TASK = 6
  REQUEST_SPELL_CAST = 7
  ACCEPT_BATTLE = 8
  PING = 9
end